# Generated by Django 4.2.3 on 2023-08-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinuser',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
