# Generated by Django 4.2.3 on 2023-08-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_coinuser_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinuser',
            name='publicKey',
            field=models.CharField(default='hey', max_length=100),
            preserve_default=False,
        ),
    ]
