# Generated by Django 4.2.3 on 2023-08-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_coinuser_publickey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinuser',
            name='privateKey',
        ),
        migrations.RemoveField(
            model_name='coinuser',
            name='publicKey',
        ),
    ]
