# Generated by Django 4.2.3 on 2023-08-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_coinuser_privatekey_remove_coinuser_publickey'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinuser',
            name='privateKey',
            field=models.CharField(default='hp', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coinuser',
            name='publicKey',
            field=models.CharField(default=('h', 'p'), max_length=100),
            preserve_default=False,
        ),
    ]
